server:
  port: 8040

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: url-gen-service
  datasource:
    username: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/notebin_db'
    password: 'wRGr3+5c'
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 100
          max-idle: 20
          min-idle: 10
      timeout: 2000