server:
  port: 8000

spring:
  application:
    name: user-service
  datasource:
    username: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/notebin_db'
    password: 'wRGr3+5c'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

mailgun:
  api:
    key: 'a3d9416faaf23b3550bdbc7a28b9ca85-623e10c8-e4284d05'
  domain: 'sandbox5e90a657244040cc87c85e7278912058.mailgun.org'