server:
  port: 8000

spring:
  application:
    name: user-service
  datasource:
    username: 'postgres'
    url: 'your-db-url'
    password: 'tour-db-password'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true