server:
  port: 8000

spring:
  application:
    name: user-service
  datasource:
    username: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/notebin_db'
    password: 'your_password_here'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true