server:
  port: 8090

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: notification-service
  datasource:
    username: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/notebin_db'
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: kafka:9092,localhost:9093  # Comma-separated list of broker addresses
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest  # Reset to earliest offset on startup
    producer:
      retries: 0  # Number of retries for sending messages

mailgun:
  api:
    key: 'key'
  domain: 'domain'
