server:
  port: 8020

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: notes-service
  datasource:
    username: 'postgres'
    url: 'your-db-url'
    password: 'your-db-password'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

azure:
  storage:
    account-url: 'your-storage-url'
    sas-token: 'your-sas-token'