server:
  port: 8020

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: notes-service
  datasource:
    username: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/notebin_db'
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

azure:
  storage:
    account-url: 'account-url'
    sas-token: 'sas-token'

mailgun:
  api:
    key: 'key'
  domain: 'domain'