server:
  port: 8020

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: notes-service
  datasource:
    username: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/notebin_db'
    password: 'your_password_here'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

azure:
  storage:
    account-url: 'your_account_url_here'
    sas-token: 'your_sas_token_here'